### ISSUE TITLE
How to generate parameters for different number of control points in gamut mapping

### ISSUE THREAD

**Issue by yaoyuannnn** [cucapra/approx-vision#5]
Hi,

I noticed that the default number of control points for the gamut mapping stage is set to 3702, which maybe a bit too large for me to test. Is there any way to generate the control points, weights, coefficients for gamut mapping?

**Comment by mbuckler** [comment]
Hey! 

Our pipeline is an augmented version of this [reversible imaging pipeline](https://github.com/mbuckler/ReversiblePipeline). The page that used to host the code for learning gamut mapping is [here](https://www.comp.nus.edu.sg/~brown/radiometric_calibration/) but unfortunately the site appears to be down. This is possibly because the PI on the project [Michael S. Brown](https://www.eecs.yorku.ca/~mbrown/) has moved to York University. We've emailed him in the past with questions so I'm sure he would respond if you were to ask him for the training code.

**Comment by yaoyuannnn** [comment]
Thanks for the pointer Mark!

**Comment by mbuckler** [comment]
You're quite welcome
