### ISSUE TITLE
models

### ISSUE THREAD

**Issue by pmcrodrigues** [cucapra/approx-vision#7]
Is it possible to find other camera models online? Other than the nikon one you provide?

**Comment by mbuckler** [comment]
Our pipeline is an augmented version of this [reversible imaging pipeline](https://github.com/mbuckler/ReversiblePipeline). The page that used to host additional models as well as the code needed to learn new models is [here](https://www.comp.nus.edu.sg/~brown/radiometric_calibration/) but unfortunately the site appears to be down. This is possibly because the PI on the project [Michael S. Brown](https://www.eecs.yorku.ca/~mbrown/) has moved to York University. We've emailed him in the past with questions so I'm sure he would respond if you were to ask him for additional models or the training code to make new models.

**Comment by pmcrodrigues** [comment]
Thank you very much, I'll do that.
